### ISSUE TITLE
Initial impressions

### ISSUE THREAD

**Issue by TheGam1ngWizard** [DerDiemen/eclipsephase#1]
Hi DerDiemen,

I'm very thankful for your system, and am very impressed. Just wanted to make a list of 'initial things' I noticed that might make it troublesome to use your sheet.

So far the things I've noticed are:
- Ego doesn't have a flex value (its all on morph, should be added between both.)
- Custom/Exotic skills don't have Specialization Fields (Can be put into the name, but should be easily fixable)
- All gear/equipment/traits/ect has to be made as a foundry 'item' and dragged in (irritating, but as long as players have item creation permissions should be fine, more of a workflow peeve.)
- Can't have multiple ID's (Can use a journal page for the time being)
- Psi is missing (Can use a journal page for the time being)
- Can't have multiple Morphs - This is a biggie, commonly players have multiple morphs and this makes it troublesome for them.
- It applies negatives against guns checks for 'No Smartgun' and I can't figureout how to resolve that. - Any modifiers like this should be checkboxes while rolling since there are many scenarios I can imagine when this wouldn't apply even if they didn't have a smartgun. 
- NPC's don't have motivations, this is important from a GM standpoint- NPCS need to have the same motivations so as a GM we can track that. 
- NPC's have all pools, while a good option, they should also have a 'threat' pool field instead of the nuanced view.
- NPC's don't have Ware or Morph traits, these are also important for tracking things.

**Comment by DerDiemen** [comment]
Heya Gam1ngWizard,

Thanks for having a look into the system and the very valuable feedback coming with this! 
As to your remarks:

- **Ego Flex** will be added in the next release, still searching for the most natural tab to place it though, but I'm sure I figure something out.
- **Exotic Skill Specs**: I was under the impression that these are not specializable. But I definitely give it another look in the. Will be added to the list.
- **Gear**: I see the pain point. I'm planning to create a compendium with this system so all the standard items from the core rules are in there. This is planned for a later release.
- **Multiple IDs**: A Candidate for the next release.
- **Psi**: Psi is in, it's just still my homebrew variant (which does not diverge too much from the real thing, but still). You can activate the Psi-Tab by adding an "Aspect" which is my name for "Sleight". This will be definitely changed in the next 0.0.X release.
- **Multiple Morphs**: Totally feel you, unfotunately that's also a big on my end, since I did not yet got my head around how to implement it, since you need to "Activate" a morph, which sets all the others to "inactive" and then changes some pools and the durability calculation. Therefore definitely something I will work on, but I do not see it before 0.4.7 - 0.5
- **Smartgun Malus**: This is a bug I will correct this week. Sorry for the inconvenience
- **NPC motifs**: Interessting point. I didn't think about this, but will add it maybe already this week, since it's a relatively small change.
- **NPC threat**: Another good one! Definitely something I'll add soon.
- **NPC Ware**: I actually tried to reduce the similarity between NPCs and Characters and drew the line at the point where gear & ware management gets really important (I know body snatching agents are a thing, but you, as a GM, can still decide what stuff was in there or not). So I'm not too sure, that I'll add this yet, since you also can just create another Player Character to get the full blown experience - But I may think about it again.

**Comment by TheGam1ngWizard** [comment]
Thanks for your response!
- Exotic skills are specilizable since its 'This is a catch-all category for less-common skills.' (pg:48 ep2e)
- Compendium would be helpful, and make it easier for players to convert sheets.
- Now that I know what to look for, I was able to get the Psi panel pulled up- and chuckle at how Psi-Chi can have an infection mod (haha, insanity go brr)

Thanks for taking a look and responding to my comments! I look forward to watching how this progresses!

**Comment by DerDiemen** [comment]
Hey there, 

thanks again for your comments - many of them have been tackled in the current version. As mentioned: Multiple bodies will still be a bit down the line. Next to come will be the compendium with pre created gear in it. 

For a full list of all the updates made, please refer to the release notes.

I close this for now
