### ISSUE TITLE
Feature Request: Gear Cache

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#2]
Something that I think would be great is the ability to add gear to different groups in order to maintain caches around.  and separating mission loadout gear from your owned gear.

**Comment by TheGam1ngWizard** [comment]
Would also work as gear packs (for the prefab backgrounds/career groups)

**Comment by DerDiemen** [comment]
Hey there,

sorry for the late response, I needed to get my head clear after the first release. 

About the request: It IS planned to have simple checkboxes in front of all items of signal which ones are "actively" worn and which are "in a stash of some sort". 

Adding gear to groups is - for my understanding - a matter of a drag an drop interface which is not yet planned, since more urgent topics (e.g. multiple sleeves) are still on my plate and unfortunately even more complex than I thought. 

The "checkbox"-solution will be hopefully implemented soon(tm) though.

**Comment by DerDiemen** [comment]
After a couple of tests and releasing the multi-body solution I now also created the option to set Gear "at hand" so show whether the character has it with them or not. It's not too beautiful but functional for the moment and I think I'll leave it this way (graphic wise) until the next bing interface revamp (which will definitely come eventually)

Please let me know your thoughts on this. I'm testing this currently in my own campaign and will release it once I'm sure it won't break anything.

![unknown](https://user-images.githubusercontent.com/9768405/116469680-b87efc00-a872-11eb-8f0a-7e1a23aa10e6.png)

**Comment by DerDiemen** [comment]
Closed due to a first solution has been implemented. Will be revisited during 0.8.x of Foundry VTT
