### ISSUE TITLE
Rep scores for NPCs

### ISSUE THREAD

**Issue by xyleth** [DerDiemen/eclipsephase#23]
Hi,

Thanks so much for putting this module together, it looks fantastic.  I'm taking it into battle, as it were, this coming weekend as a way of managing NPCs and combat encounters even though we're playing around a table.

Speaking of NPCs - is there a way to get Rep trackers on their sheets?  There are some long-lived NPCs in my campaign that would be useful to track Rep.  Right now I'm just using the notes field.

Either that or I make them PCs with a full sheet - is there a downside to doing that for NPCs (e.g. does the module treat them differently?).

**Comment by DerDiemen** [comment]
Hey Xyleth,

Thank you for the feedback - always warms my heart <3. To your question:

In general the main difference between the different character sheets is the number of options on them. Also - as you just mentioned - the character sheets are missing the threat-values, which are here replaced by the four other pools available.

The idea is, that everything is basically a goon, as long as it is not an important NPC. NPCs have far more options to them e.g. goals. Now Rep is basically meant to be a help for the GM to determine which kind of gear a player can affort and which not. As a GM though, you can basically just decide on what makes sense for your NPC, as no one can tell you otherwise. 

For this reason I believe it a bit misleading to introduce a player ressource to the NPC sheet, that is meant to limit characters, not the game author. 

That said: If you want to use a PC sheet for an NPC the main difference is, that everything takes a bit more room (Because players like it to get more details to what they can do with their baby) and - as mentioned - missing Threat level, which I would then just use Flex for, as it is already some kind of multi-pool, and all you would need to keep in mind would then be, that they can actually use it for every other pool as well.

**Comment by DerDiemen** [comment]
Thanks for your comment, this issue is closed for now. If there's anything still blocking what you try to achieve, please let me know in a new one!

- closed
