### ISSUE TITLE
Compendium issues & typoes

### ISSUE THREAD

**Issue by contraile** [DerDiemen/eclipsephase#3]
First of all, absolutely massive thank you for your work on this module. I just switched over to Foundry for the last arc of my EP2 campaign, and it's already much more comfortable than what I was using previously. The polish and level of automation on the sheets is astonishing.

Some issues with compendium entries I've spotted so far:
- Multi-Tasking ware seems to be missing completely
- Submachine Gun weapon is missing its fire mode and other stats
- Viewers gear item is listed twice

Minor typoes in entry names:
- Ressources -> Resources (Ego trait)
- Indentity Crisis -> Identity Crisis (Ego trait)
- Real World Naivité -> Real World Naiveté (Ego trait)
- Preassure Adaptation -> Pressure Adaptation (Ware)
- Innocuos Looks -> Innocuous Looks (Morph trait)
- Planned Obsolence -> Planned Obsolescence (Morph trait)
- Psi Vulnarability -> Psi Vulnerability (Morph trait)

**Comment by DerDiemen** [comment]
Hey Contraile,

Thank you for your kind words and for reporting the issue! And right on time. It's planned to release the next big thing with the Foundry 0.8.x stable release next week, so I will definitely include your feedback in there (I also noticed some other missing Morph-Traits recently I'm about to add)

It's very to have some people to check on typos and missing things since I am a) obviously no native speaker and b) only one person. So please: Whenever you finde some spelling issues or missing stuff, feel free to send a consolidated list like this one. It really helps to speed up my work :)

All the best

Diemen

**Comment by DerDiemen** [comment]
Changed the typos and published the changes with the new release.
