### ISSUE TITLE
Apps have no place or don't work

### ISSUE THREAD

**Issue by Mirsellus** [DerDiemen/eclipsephase#42]
Tried to put the Apps in inventory, expected them to work like Psi with a separate menu, but instead nothing happened. I suspect they are broken. Seems to be affecting all the players in my game.

Also, a sort function or gear categories would be helpful. I realized I was missing stuff, but didn't realize what was wrong until I went through every type of gear separately.

**Comment by Mirsellus** [comment]
Also, lesser note, no way to spend flex points for narrative control:

**Comment by DerDiemen** [comment]
Hey there,

So first of all, this sheet does not really support the quite over-complex hacking rules EP sports, as I'm not seeing them as really essential, given the huge amount of work they would introduce to the system. (If you want to convince me otherwise, feel free to add me on Discord (Jorra#7357))

That said "apps" have been added by a third party and I now integrated them properly to the sheet in the latest version of the system itself (https://github.com/DerDiemen/eclipsephase/releases/tag/v0.8.6)

Since v0.8.6 has a lot of new features, spending points on something else than just swapping results habe been added as well.

Thank you for raising these issues anyhow!
