### ISSUE TITLE
Minor formatting problems

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#52]
NPC/Threat sheets
No padding after quick add ranged/melee/armor
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/3025d301-81b6-4b2f-97f1-6b55534965af)
No space between + and Quick Add Armor
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/2e60587c-aef1-4702-83e9-03c503291507)
No padding after + in ranged/melee weapons
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/5baff290-9396-48d8-9239-d73ba497443f)

PC sheets
No space between SLEEVED and morph name
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/67222014-8fb1-4e8f-89af-63a2db3eb3b1)
More drop down menu smaller than weapon box
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/3032474b-d3cf-42a1-a190-d441322fc602)

**Comment by DerDiemen** [comment]
I love this a lot! Thank you so much. I‘ll definitely have a look into these :) Keep these coming whenever you come across something, as it‘s kinda tedious for me to go through everything while concentrating on other stuff.

**Comment by ava5627** [comment]
Bots
Aptitudes have full name instead of abbreviation (Also happens for sample characters)
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/71bd4dc8-f1cd-4c31-8b7f-f8f900a48415)
Durability and death rating display messed up until any field in the bot's morph is edited
![image](https://github.com/DerDiemen/eclipsephase/assets/40039652/386dcdc8-ae8a-4a44-b370-9a78740f5ef9)

Peripherals
no way to automatically roll their stats

Morph
Limited to exactly two movement types, Reapers and Arachnoids have four

Weapons
Railguns should have 2x ammo and 1.5x range

**Comment by DerDiemen** [comment]
Please do not mix new features with minor formatting issues. 

Reasons for many of these last posted ones is „Doesn‘t have priority yet“. 

Best open one or more new issues so I can properly funnel them when their time comes.

**Comment by DerDiemen** [comment]
Many of these issues have been fixed in the current release (0.9.5).

Please note that bots have been deleted and will most likely not make a comeback in the state they have been in back then. You can instadt use items to add peripherals to a character (or NPC). These will become rollable soon (TM) but most likely after v1.0

Sample characters will be updated after v1.0 as well so they're here to stay.

Morphs will undergo a huge revamp during release 1.1 or 1.2 so there are no plans of introducing any changes to morphs at this point in time.
