### ISSUE TITLE
NPC and Threat Initiative modifier added Twice

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#57]
When rolling initiative NPCs and Threats have both calculated initiative (REF + INT / 5) and the "Ini mod" field added to their roll.

**Comment by DerDiemen** [comment]
I‘m not entirely sure whether I understand this correctly, but I believe this is by design. 

So it is planned that you can manually add a modifier to your Thread‘s INI - But obviously the regular Ini is still to be used. 

Maybe you can elaborate a bit on this issue. 

Thank you for reporting anyway.

**Comment by ava5627** [comment]
Ok, that makes sense. I initially thought it was for regular initiative and didn't realize initiative was calculated already. Maybe add something next to the text box like 1d6 + [initiative] + [text box] to make it clearer it's not for the regular initiative.

**Comment by DerDiemen** [comment]
This has been adressed and will be reflected in the upcoming update.
