### ISSUE TITLE
Players are not able to modify their pools

### ISSUE THREAD

**Issue by herrozerro** [DerDiemen/eclipsephase#61]
Related to #54, players cannot edit their own pools.  

Solution:  Add a setting to the GM can toggle player control over the sheet.

**Comment by DerDiemen** [comment]
Hey there, 
I‘m trying to push the last feature update till 1.0 this week and will then probably fix these two issues on my last stretch before releasing 1.0

**Comment by DerDiemen** [comment]
Now... in order to modify pools this would lead to quiet the UI - Change which I'm not sure how to solve yet. 

The main issue is, that by making the values editable I have to get rid of the "close" button that lets you close the pool spending menu.

![Screenshot 2023-12-17 at 13 57 28](https://github.com/DerDiemen/eclipsephase/assets/9768405/19d7a4b7-5b94-471f-a178-bae3968dfc22)
![Screenshot 2023-12-17 at 13 57 34](https://github.com/DerDiemen/eclipsephase/assets/9768405/1b3bc0a6-71af-4c25-9c3d-531ce84a9702)

Doing this might then lead to the question "how to I close the menu" - while clicking the pool again would do exactly this. My first idea was "clicking somewhere else on the sheet" but this solution never worked until now (code wise) and I think it's currently to much to revisit this solution, as it would be more like a new feature to me.

Leaves the question: How would you solve this in a maintainable manner? Any ideas?

**Comment by DerDiemen** [comment]
Alternatively one could argue, that this menu isn't needed anymore once pools are editable manually... could be a solution. What do you think @herrozerro ?

**Comment by herrozerro** [comment]
What if you added the pools to that menu?

**Comment by DerDiemen** [comment]
Actually not the worst idea - what do you think about this?
![Screenshot 2023-12-17 at 15 50 49](https://github.com/DerDiemen/eclipsephase/assets/9768405/1b54ba06-8221-4f6f-bd3b-f8f49cfad8c7)
![Screenshot 2023-12-17 at 15 50 58](https://github.com/DerDiemen/eclipsephase/assets/9768405/24330c91-b715-4e7b-b509-2dbcad0527c1)

**Comment by herrozerro** [comment]
Love it

**Comment by DerDiemen** [comment]
Great! Will be part of the next release, probably coming today...

Thanks for your support!
