### ISSUE TITLE
Using Roll Heal with empty timeframe textbox always uses 1 hour regardless of selected unit

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#63]
Changing the unit in roll heal to days or weeks does not change the timeframe from hours if the textbox is empty. Same issue in mental health only with days instead of weeks

**Comment by DerDiemen** [comment]
Oh you mean it should register it as „1 week“ in the case of selecting „weeks“ without a value in the input field?

**Comment by DerDiemen** [comment]
Ich believe that I found the reason: Giving no input in the input field leads to defaulting to 0 - A week in that example multiplies the time measured in hours by 168 which is still 0 and then defaults to 1 hour since 0 hours is not possible.

I'll change the input field to defaulting to 1 if no input has been made!

**Comment by DerDiemen** [comment]
This has been implemented and will be part of the upcoming release! Thanks for bringing this up!
